source: /my-first-hugo-site/
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
  posts:
    path: content/posts
    name: Posts
    icon: event_available
    glob:
      - '!_index.md'
  data:
    path: data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
paths:
  static: static
  uploads: static/uploads
timezone: Europe/London
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
